export const GET_POKEMONS_REQUEST = 'GET_POKEMONS_REQUEST';
export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS';
export const GET_POKEMONS_FAILURE = 'GET_POKEMONS_FAILURE';

export const GET_POKEMON_DETAIL_REQUEST = 'GET_POKEMON_DETAIL_REQUEST';
export const GET_POKEMON_DETAIL_SUCCESS = 'GET_POKEMON_DETAIL_SUCCESS';
export const GET_POKEMON_DETAIL_FAILURE = 'GET_POKEMON_DETAIL_FAILURE';

export const GET_MOVES_REQUEST = 'GET_MOVES_REQUEST';
export const GET_MOVES_SUCCESS = 'GET_MOVES_SUCCESS';
export const GET_MOVES_FAILURE = 'GET_MOVES_FAILURE';

export const GET_SPECIES_REQUEST = 'GET_SPECIES_REQUEST';
export const GET_SPECIES_SUCCESS = 'GET_SPECIES_SUCCESS';
export const GET_SPECIES_FAILURE = 'GET_SPECIES_FAILURE';
